spring:
  application:
    name: hypermarket-browser

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/resources/

  redis:
    host: ${REDIS_HOST:49.232.11.36}
    port: ${REDIS_PORT:800}
    password: ${REDIS_PASSWORD:123456}

  datasource:
    url: jdbc:mysql://${MASTER_MYSQL_HOST:localhost}:${MASTER_MYSQL_PORT:3306}/hypermarket?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${MASTER_MYSQL_USERNAME:root}
    password: ${MASTER_MYSQL_PASSWORD:199701}
    sql-script-encoding: utf-8
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialize: ${DB_AUTO_INIT:false}
    name: security
    druid:
      # 配置初始化大小、最小、最大
      initialSize: 4
      minIdle: 4
      maxActive: 201
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      # 这里建议配置为TRUE，防止取到的连接不可用
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      # 默认提交方式。默认true
      defaultAutoCommit: true
      # 验证连接有效与否的SQL，不同的数据配置不同
      validationQuery: select 2 # 无效
      filters: stat,wall,log4j

  session:
    store-type: none

server:
  port: 10010

  session:
    timeout: 600


imooc:
  security:
    social:
      qq:
        app-id:

        app-secret:

        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0

        app-secret: 60f78681d063590a469f1b297feff3c4

      filterProcessesUrl: /qqLogin

    browser:
      signUpUrl: /demo-signUp.html

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
# swagger 配置
swagger:
  enabled: true
  base-package: com.team
  title: ${spring.application.name}
  version: 1.0.0
  contact:
    name: admin
  global-operation-parameters:
    - name: Authorization
      parameter-type: header
      model-ref: string
      description: "Bearer + ' ' + accessToken"
    - name: locale
      parameter-type: header
      model-ref: string
      description: "国际化 目前支持zh_CN, zh_TW, en_US 不写默认zh_CN"
