version: '3'
services:

  maxbase-weekly-report:
    container_name: hypermarket-backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: hypermarket-backend:theversion
    privileged: true
    restart: always
    ports:
      - 10010:10010
    volumes:
      - /opt/logs/hypermarket-backend:/opt/logs/hypermarket-backend
      - /data/resources:/resources
    environment:
      - SQL_ENV_NAME=dev
      - IP_ADDRESS=theip
      - REDIS_HOST=theip
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispwd
      - MASTER_MYSQL_HOST=mysqlhost
      - MASTER_MYSQL_PORT=mysqlport
      - MASTER_MYSQL_USERNAME=theuser
      - MASTER_MYSQL_PASSWORD=thedbpwd
      - LOG_PATH=/opt/logs/hypermarket-backend
      - LOG_FILE=hypermarket-backend
      - LOG_MAX_FILE_SIZE=100MB
      - LOG_MAX_HISTORY_DAYS=30
      - LOG_ROOT_LEVEL=info
      - DB_AUTO_INIT=false
      - TZ=Asia/Shanghai

